language: elixir
elixir:
  - 1.11.0
otp_release:
  - 22.0
script:
  - if [[ `elixir -v` = *"1.11"* ]]; then mix format --check-formatted; fi
  - MIX_ENV=test mix test --trace --cover
  - MIX_ENV=test mix credo --strict
services:
  - redis-server
sudo: false
