language: elixir
elixir:
  - 1.6.6
  - 1.7.3
otp_release:
  - 21.0
script:
  - if [[ `elixir -v` = *"1.7"* ]]; then mix format --check-formatted; fi
  - MIX_ENV=test mix test --trace --cover
services:
  - redis-server
sudo: false
